title: About Me!
author: Leona Jain
email: leonahco10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is for you guys to learn a little bit about me. Hope you enjoy!
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
